### ISSUE TITLE
function vector_resize_for_index (./helpers/vector.c)

### ISSUE THREAD

**Issue by 1040403998** [nibblebits/PeachCompiler#5]
while updating the parameter "vector->mindex", I think it should somehow be "vector->mindex = start_index + total_elements + VECTOR_ELEMENT_INCREMENT", instead of "vector->mindex = start_index + total_elements". I'm not sure if this is an issue or there is something wrong with my understanding. Please check for that.

**Comment by nibblebits** [comment]
Hello,
Please can you elaborate n why you think this so i can see, use the code snippet feature if you dont mind so its easier for me to read

Thanks

**Comment by nibblebits** [comment]
Issue was closed for now, if you have more evidence of an issue please let me know
