### ISSUE TITLE
Possible Improvement for Makefile main file

### ISSUE THREAD

**Issue by fedi-nabli** [nibblebits/PeachCompiler#6]
In the clean method, instead of having manually to create the main file in order to make clean, I suggest checking if the file exits, and if it does, we delete it.

This is my solution:
clean:
	if [ -f ./main ] ; \
	then \
		rm ./main ; \
	fi;
	rm -rf ${OBJECTS}

**Comment by nibblebits** [comment]
Thanks for adding that helpful suggestion, students feel free to use this if you wish, but it is not mandatory and is just a convenience
